modLoader="klf"
loaderVersion="[1,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/FrozenBlock/Configurable-Everything/issues"

[[mods]]
    modId="configurable_everything"
    version="${mod_version}"
    displayName="Configurable Everything"
    displayURL="https://modrinth.com/mod/configurable-everything"
    logoFile="assets/configurable_everything/icon.png"
    authors="FrozenBlock"
    description='''
Makes various aspects of Minecraft configurable.
    '''

[[mixins]]
config="configurable_everything.biome_placement.mixins.json"

[[mixins]]
config="configurable_everything.datafixer.mixins.json"

[[mixins]]
config="configurable_everything.datapack.mixins.json"

[[mixins]]
config="configurable_everything.entity.mixins.json"

[[mixins]]
config="configurable_everything.fluid.mixins.json"

[[mixins]]
config="configurable_everything.game.mixins.json"

[[mixins]]
config="configurable_everything.item.mixins.json"

[[mixins]]
config="configurable_everything.loot.mixins.json"

[[mixins]]
config="configurable_everything.recipe.mixins.json"

[[mixins]]
config="configurable_everything.screenshake.mixins.json"

[[mixins]]
config="configurable_everything.sculk_spreading.mixins.json"

[[mixins]]
config="configurable_everything.splash_text.mixins.json"

[[mixins]]
config="configurable_everything.structure.mixins.json"

[[mixins]]
config="configurable_everything.tag.mixins.json"

[[mixins]]
config="configurable_everything.world.mixins.json"

[[ dependencies.configurable_everything ]]
    modId="neoforge"
    type="required"
    versionRange="[~26.2-,)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.configurable_everything ]]
    modId="minecraft"
    type="required"
    versionRange="[~26.2-,)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.configurable_everything ]]
    modId="frozenlib"
    type="required"
    versionRange="[3.0,)"
    ordering="NONE"
    side="BOTH"
