name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_URL: ${{secrets.SNAPSHOT_MAVEN_URL}}
      MAVEN_USERNAME: ${{secrets.MAVEN_USERNAME}}
      MAVEN_PASSWORD: ${{secrets.MAVEN_PASSWORD}}
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          download_url="https://cdn.azul.com/zing-zvm/ZVM23.02.0.0/zing23.02.0.0-3-jdk17.0.6-linux_x64.tar.gz"
          wget -O zing23.02.0.0-3-jdk17.0.6-linux_x64.tar.gz $download_url
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build -PuseThirdPartyMods=false
      - name: Extract current branch name
        shell: bash
        # bash pattern expansion to grab branch name without slashes
        run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
        id: ref
      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ConfigurableEverything-Artifacts-${{ steps.ref.outputs.branch }}
          path: build/libs/
